"""
dart_quotex/signals/algo_patterns.py
OTC Algorithmic Pattern Detection Suite
=========================================
Pricing engines for OTC binary options are deterministic software programs.
Unlike real exchange markets driven by millions of human participants, OTC
prices are generated by algorithms that — by their very nature — exhibit:

  · Fixed-interval resets and oscillations
  · Round-number gravitational pull
  · Predictable consecutive-run limits
  · Mean-reversion on a fixed candle timer
  · Volatility expansion/contraction cycles
  · Artificial body-to-wick ratios
  · Synthetic tick-size patterns
  · Sequential price templates

None of these are visible to a human watching a chart.
All of them are measurable with statistics.

This module contains 8 specialised detectors plus a master scanner:

  1.  SequenceDetector        — after N green/red in a row, what happens?
  2.  PriceMagnetDetector     — does price cluster around round numbers?
  3.  OscillationDetector     — does price oscillate in a fixed range?
  4.  MeanReversionTimer      — how many candles until price reverts?
  5.  VolatilityCycleDetector — expansion → contraction → expansion cycle
  6.  BodyRatioPatternDetector — are certain body/wick ratios predictive?
  7.  TickArtifactDetector    — synthetic tick generation patterns
  8.  RunLengthDetector       — how long do trends run before reversing?

  AlgoPatternScanner          — runs all 8, returns best live signal

Usage
-----
    scanner = AlgoPatternScanner()
    scanner.fit(db.get_candles("EURUSD_OTC", 60, limit=5000))
    scanner.save("models/algo_patterns.json")

    # Live:
    scanner.load("models/algo_patterns.json")
    sig = scanner.signal(df_recent)
    if sig.has_pattern:
        print(sig)   # direction, confidence, which detector fired
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats

log = logging.getLogger(__name__)

_MIN_N    = 25     # minimum observations to trust a pattern
_P_CUTOFF = 0.05   # significance threshold
_MIN_CONF = 0.55   # minimum confidence to emit a signal


# ──────────────────────────────────────────────────────────────────────────────
# Common signal container
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class AlgoSignal:
    has_pattern:  bool
    direction:    str    # "CALL" | "PUT" | "NEUTRAL"
    confidence:   float  # 0-1
    detector:     str    # which detector fired
    description:  str
    p_value:      float = 1.0
    n_samples:    int   = 0
    extra:        dict  = field(default_factory=dict)

    def __str__(self) -> str:
        return (f"AlgoSignal({self.direction} conf={self.confidence:.2f} "
                f"from={self.detector} | {self.description})")


_NEUTRAL = AlgoSignal(False, "NEUTRAL", 0.0, "none", "No pattern")


# ──────────────────────────────────────────────────────────────────────────────
# 1. Sequence Detector
#    "After N consecutive bullish candles, what is the next candle?"
# ──────────────────────────────────────────────────────────────────────────────

class SequenceDetector:
    """
    Detects what tends to happen after N candles of the same direction.

    Example:  After exactly 3 consecutive bearish candles, 78% of the time
              the 4th candle is bullish  (p=0.003, n=47)
              → strong CALL signal on the 4th candle
    """

    name = "sequence"

    def __init__(self, max_run: int = 8) -> None:
        self.max_run = max_run
        # Table: {(direction, run_length): [outcomes]}  outcome=1 bullish, 0 bearish
        self._table: Dict[Tuple[str, int], List[int]] = defaultdict(list)
        self._signals: Dict[str, AlgoSignal] = {}

    def fit(self, df: pd.DataFrame) -> None:
        self._table.clear()
        closes  = df["close"].values.astype(float)
        opens   = df["open"].values.astype(float)
        bullish = (closes >= opens).astype(int)

        run     = 0
        run_dir = bullish[0]

        for i in range(1, len(bullish)):
            if bullish[i - 1] == run_dir:
                run += 1
            else:
                run = 1
                run_dir = bullish[i - 1]

            if run <= self.max_run:
                key = ("bull" if run_dir == 1 else "bear", run)
                self._table[key].append(int(bullish[i]))

        self._signals = {}
        for (run_dir, run_len), outcomes in self._table.items():
            n = len(outcomes)
            if n < _MIN_N:
                continue
            bull_count = sum(outcomes)
            bull_rate  = bull_count / n
            res        = scipy_stats.binomtest(bull_count, n, 0.5)
            p          = float(res.pvalue)
            if p >= _P_CUTOFF or abs(bull_rate - 0.5) < 0.08:
                continue
            direction = "CALL" if bull_rate > 0.5 else "PUT"
            conf      = _calc_conf(bull_rate, p, n)
            key       = f"{run_dir}_{run_len}"
            self._signals[key] = AlgoSignal(
                has_pattern=True,
                direction=direction,
                confidence=conf,
                detector=self.name,
                p_value=p,
                n_samples=n,
                description=(
                    f"After {run_len} consecutive {run_dir} candles: "
                    f"next is {direction} {bull_rate:.0%} of the time"
                ),
                extra={"run_dir": run_dir, "run_len": run_len,
                       "bull_rate": bull_rate},
            )
        log.debug("SequenceDetector: %d patterns", len(self._signals))

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        """Check what the current candle run length is and look up signal."""
        if not self._signals:
            return _NEUTRAL
        closes  = df["close"].values.astype(float)
        opens   = df["open"].values.astype(float)
        bullish = (closes >= opens).astype(int)
        if len(bullish) < 2:
            return _NEUTRAL

        # Current run direction and length
        run_dir = "bull" if bullish[-2] == 1 else "bear"
        run_len = 1
        for i in range(len(bullish) - 3, -1, -1):
            if bullish[i] == bullish[-2]:
                run_len += 1
            else:
                break

        key = f"{run_dir}_{run_len}"
        return self._signals.get(key, _NEUTRAL)

    def to_dict(self) -> dict:
        return {k: _sig_to_dict(v) for k, v in self._signals.items()}

    def from_dict(self, d: dict) -> None:
        self._signals = {k: _sig_from_dict(v) for k, v in d.items()}


# ──────────────────────────────────────────────────────────────────────────────
# 2. Price Magnet Detector
#    "Does price cluster around round numbers or specific price levels?"
# ──────────────────────────────────────────────────────────────────────────────

class PriceMagnetDetector:
    """
    OTC pricing engines often exhibit gravitational pull toward round numbers
    (1.10000, 1.10500) or regularly-spaced price levels (every 10 pips).

    This detector:
      · Identifies the most-visited price levels (bins)
      · Measures whether price rebounds from those levels
      · Signals: if current price is near a magnet level and moving toward it
        → expect it to reach and bounce
    """

    name = "price_magnet"

    def __init__(self, pip_size: float = 0.0001, n_bins: int = 100) -> None:
        self.pip_size = pip_size
        self.n_bins   = n_bins
        self._magnet_levels: List[float] = []
        self._bounce_rates: Dict[float, Tuple[float, float, int]] = {}  # level→(bull_rate, p, n)

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        opens  = df["open"].values.astype(float)
        bull   = (closes >= opens).astype(int)

        price_min, price_max = closes.min(), closes.max()
        bin_size = (price_max - price_min) / self.n_bins

        if bin_size < self.pip_size:
            return

        # Count visits per bin
        bins   = np.floor((closes - price_min) / bin_size).astype(int)
        counts = np.bincount(bins, minlength=self.n_bins)
        mean_c = counts.mean()
        std_c  = counts.std() + 1e-9

        # Levels visited significantly more often than average
        magnet_bins = np.where(counts > mean_c + 1.5 * std_c)[0]
        self._magnet_levels = [
            round(price_min + (b + 0.5) * bin_size, 6)
            for b in magnet_bins
        ]

        # For each magnet level: what's the next candle's direction?
        self._bounce_rates = {}
        for level in self._magnet_levels:
            near = np.abs(closes - level) < bin_size * 0.8
            near_indices = np.where(near)[0]
            next_indices = near_indices[near_indices < len(bull) - 1] + 1
            if len(next_indices) < _MIN_N:
                continue
            outcomes   = bull[next_indices]
            bull_count = int(outcomes.sum())
            n          = len(outcomes)
            bull_rate  = bull_count / n
            res        = scipy_stats.binomtest(bull_count, n, 0.5)
            p          = float(res.pvalue)
            if p < _P_CUTOFF and abs(bull_rate - 0.5) > 0.08:
                self._bounce_rates[level] = (bull_rate, p, n)

        log.debug(
            "PriceMagnetDetector: %d magnet levels, %d with bounce signal",
            len(self._magnet_levels), len(self._bounce_rates),
        )

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if not self._bounce_rates:
            return _NEUTRAL

        current_price = float(df["close"].iloc[-1])
        closes        = df["close"].values.astype(float)
        price_range   = closes.max() - closes.min()
        proximity     = price_range * 0.01  # within 1% of range = "near"

        best: Optional[AlgoSignal] = None
        for level, (bull_rate, p, n) in self._bounce_rates.items():
            dist = abs(current_price - level)
            if dist > proximity:
                continue
            direction = "CALL" if bull_rate > 0.5 else "PUT"
            conf      = _calc_conf(bull_rate, p, n)
            if best is None or conf > best.confidence:
                best = AlgoSignal(
                    has_pattern=True,
                    direction=direction,
                    confidence=conf,
                    detector=self.name,
                    p_value=p,
                    n_samples=n,
                    description=(
                        f"Price magnet at {level:.5f} "
                        f"({dist/self.pip_size:.1f} pips away): "
                        f"{direction} {bull_rate:.0%} on approach"
                    ),
                    extra={"level": level, "distance_pips": dist / self.pip_size},
                )
        return best or _NEUTRAL

    def to_dict(self) -> dict:
        return {
            "magnet_levels": self._magnet_levels,
            "bounce_rates": {
                str(k): {"bull_rate": v[0], "p_value": v[1], "n": v[2]}
                for k, v in self._bounce_rates.items()
            },
        }

    def from_dict(self, d: dict) -> None:
        self._magnet_levels = d.get("magnet_levels", [])
        self._bounce_rates  = {
            float(k): (v["bull_rate"], v["p_value"], v["n"])
            for k, v in d.get("bounce_rates", {}).items()
        }


# ──────────────────────────────────────────────────────────────────────────────
# 3. Oscillation Detector
#    "Does price oscillate between two fixed boundaries repeatedly?"
# ──────────────────────────────────────────────────────────────────────────────

class OscillationDetector:
    """
    Many OTC pricing engines produce price that oscillates between two
    fixed boundaries over a consistent cycle length.

    Detection method:
      · Measure the distance from the current price to the rolling 50-bar high/low
      · If it has touched the boundary and is now moving away → signal

    Live signal: if price just touched the upper boundary → PUT
                 if price just touched the lower boundary → CALL
    """

    name = "oscillation"

    def __init__(self, lookback: int = 50) -> None:
        self.lookback = lookback
        self._touch_threshold: float = 0.02   # within 2% of range = "touching"
        self._upper_reversal_rate: float = 0.5
        self._lower_reversal_rate: float = 0.5
        self._upper_p: float = 1.0
        self._lower_p: float = 1.0
        self._upper_n: int = 0
        self._lower_n: int = 0

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        highs  = df["high"].values.astype(float)
        lows   = df["low"].values.astype(float)
        bull   = (closes[1:] >= closes[:-1]).astype(int)

        n = len(closes)
        upper_reversals, lower_reversals = [], []

        for i in range(self.lookback, n - 1):
            window_high = highs[i - self.lookback : i].max()
            window_low  = lows[i  - self.lookback : i].min()
            band        = window_high - window_low + 1e-9
            pos         = (closes[i] - window_low) / band

            if pos > 1.0 - self._touch_threshold:   # near upper band
                upper_reversals.append(int(bull[i]))
            if pos < self._touch_threshold:          # near lower band
                lower_reversals.append(int(bull[i]))

        def _compute(outcomes: List[int]) -> Tuple[float, float, int]:
            n_ = len(outcomes)
            if n_ < _MIN_N:
                return 0.5, 1.0, n_
            c   = sum(outcomes)
            r   = c / n_
            res = scipy_stats.binomtest(c, n_, 0.5)
            return r, float(res.pvalue), n_

        (self._upper_reversal_rate, self._upper_p,
         self._upper_n) = _compute(upper_reversals)
        (self._lower_reversal_rate, self._lower_p,
         self._lower_n) = _compute(lower_reversals)

        log.debug(
            "OscillationDetector: upper→%s %.0f%% p=%.3f  lower→%s %.0f%% p=%.3f",
            "PUT"  if self._upper_reversal_rate < 0.5 else "CALL",
            self._upper_reversal_rate * 100, self._upper_p,
            "CALL" if self._lower_reversal_rate > 0.5 else "PUT",
            self._lower_reversal_rate * 100, self._lower_p,
        )

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if len(df) < self.lookback + 2:
            return _NEUTRAL
        highs  = df["high"].values.astype(float)
        lows   = df["low"].values.astype(float)
        closes = df["close"].values.astype(float)
        window_high = highs[-self.lookback - 1 : -1].max()
        window_low  = lows[-self.lookback - 1 : -1].min()
        band        = window_high - window_low + 1e-9
        pos         = (closes[-1] - window_low) / band

        # Near upper band
        if pos > 1.0 - self._touch_threshold:
            if (self._upper_p < _P_CUTOFF and
                    self._upper_reversal_rate < 0.5 - 0.08):
                conf = _calc_conf(1 - self._upper_reversal_rate,
                                  self._upper_p, self._upper_n)
                return AlgoSignal(
                    has_pattern=True, direction="PUT",
                    confidence=conf, detector=self.name,
                    p_value=self._upper_p, n_samples=self._upper_n,
                    description=(
                        f"Price at upper oscillation band ({pos:.0%}): "
                        f"reverts down {1-self._upper_reversal_rate:.0%}"
                    ),
                )

        # Near lower band
        if pos < self._touch_threshold:
            if (self._lower_p < _P_CUTOFF and
                    self._lower_reversal_rate > 0.5 + 0.08):
                conf = _calc_conf(self._lower_reversal_rate,
                                  self._lower_p, self._lower_n)
                return AlgoSignal(
                    has_pattern=True, direction="CALL",
                    confidence=conf, detector=self.name,
                    p_value=self._lower_p, n_samples=self._lower_n,
                    description=(
                        f"Price at lower oscillation band ({pos:.0%}): "
                        f"reverts up {self._lower_reversal_rate:.0%}"
                    ),
                )
        return _NEUTRAL

    def to_dict(self) -> dict:
        return {
            "upper_rate": self._upper_reversal_rate, "upper_p": self._upper_p,
            "upper_n":    self._upper_n,
            "lower_rate": self._lower_reversal_rate, "lower_p": self._lower_p,
            "lower_n":    self._lower_n,
        }

    def from_dict(self, d: dict) -> None:
        self._upper_reversal_rate = d["upper_rate"]
        self._upper_p             = d["upper_p"]
        self._upper_n             = d["upper_n"]
        self._lower_reversal_rate = d["lower_rate"]
        self._lower_p             = d["lower_p"]
        self._lower_n             = d["lower_n"]


# ──────────────────────────────────────────────────────────────────────────────
# 4. Mean Reversion Timer
#    "How many candles after a large move before price reverts?"
# ──────────────────────────────────────────────────────────────────────────────

class MeanReversionTimer:
    """
    OTC pricing algorithms often implement mean-reversion on a fixed timer:
    after a large directional move (> 1 ATR), price almost always
    reverts within exactly N candles.

    This detector finds the dominant reversion delay N and signals
    a CALL/PUT at exactly the right moment.
    """

    name = "mean_reversion_timer"

    def __init__(self, max_delay: int = 20) -> None:
        self.max_delay = max_delay
        self._reversion_delay: int = 0
        self._after_up_direction:  str   = "NEUTRAL"
        self._after_down_direction: str  = "NEUTRAL"
        self._up_conf:   float = 0.0
        self._down_conf: float = 0.0

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        n      = len(closes)

        rets = np.diff(closes) / (closes[:-1] + 1e-9)
        atr  = np.abs(rets).rolling(14).mean().values \
            if hasattr(np.abs(rets), 'rolling') \
            else _rolling_mean(np.abs(rets), 14)

        delay_stats: Dict[int, List[int]] = defaultdict(list)

        for i in range(14, n - self.max_delay):
            if abs(rets[i]) < atr[i] * 1.5:
                continue
            is_up = rets[i] > 0
            for delay in range(1, self.max_delay + 1):
                j = i + delay
                if j >= len(rets):
                    break
                reverted = (rets[j] < 0) if is_up else (rets[j] > 0)
                delay_stats[delay].append(int(reverted))

        if not delay_stats:
            return

        # Find the delay with the highest reversion rate
        best_delay, best_rate, best_p, best_n = 0, 0.5, 1.0, 0
        for delay, outcomes in delay_stats.items():
            nn  = len(outcomes)
            if nn < _MIN_N:
                continue
            rate = sum(outcomes) / nn
            res  = scipy_stats.binomtest(sum(outcomes), nn, 0.5)
            p    = float(res.pvalue)
            if rate > best_rate and p < _P_CUTOFF:
                best_delay, best_rate, best_p, best_n = delay, rate, p, nn

        self._reversion_delay = best_delay
        if best_delay > 0 and best_rate > 0.5 + 0.08:
            self._after_up_conf   = _calc_conf(best_rate, best_p, best_n)
            self._after_down_conf = self._after_up_conf
        else:
            self._after_up_conf   = 0.0
            self._after_down_conf = 0.0

        log.debug(
            "MeanReversionTimer: best_delay=%d reversion_rate=%.1f%% p=%.4f",
            self._reversion_delay, best_rate * 100, best_p,
        )

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if (self._reversion_delay == 0 or
                not hasattr(self, "_after_up_conf") or
                self._after_up_conf < _MIN_CONF):
            return _NEUTRAL

        closes = df["close"].values.astype(float)
        if len(closes) < 16 + self._reversion_delay:
            return _NEUTRAL

        rets = np.diff(closes) / (closes[:-1] + 1e-9)
        atr  = float(np.abs(rets[-14:]).mean())

        # Check if there was a large move exactly `reversion_delay` candles ago
        idx = -(self._reversion_delay + 1)
        if abs(idx) > len(rets):
            return _NEUTRAL

        trigger_ret = rets[idx]
        if abs(trigger_ret) < atr * 1.5:
            return _NEUTRAL

        direction = "PUT" if trigger_ret > 0 else "CALL"
        return AlgoSignal(
            has_pattern=True,
            direction=direction,
            confidence=self._after_up_conf,
            detector=self.name,
            description=(
                f"Large move {self._reversion_delay} candles ago "
                f"({trigger_ret:+.4%}): mean reversion expected → {direction}"
            ),
        )

    def to_dict(self) -> dict:
        return {
            "delay":      self._reversion_delay,
            "up_conf":    getattr(self, "_after_up_conf",   0.0),
            "down_conf":  getattr(self, "_after_down_conf", 0.0),
        }

    def from_dict(self, d: dict) -> None:
        self._reversion_delay = d.get("delay", 0)
        self._after_up_conf   = d.get("up_conf", 0.0)
        self._after_down_conf = d.get("down_conf", 0.0)


# ──────────────────────────────────────────────────────────────────────────────
# 5. Volatility Cycle Detector
#    "Volatility expands, then contracts, on a fixed schedule"
# ──────────────────────────────────────────────────────────────────────────────

class VolatilityCycleDetector:
    """
    OTC algorithms often produce volatility on a repeating cycle:
    N candles of high volatility, then M candles of low volatility.

    This detector:
      · Measures ATR at every position in the cycle
      · Finds where ATR is predictably highest (→ larger moves = tradeable)
      · Finds where ATR is predictably lowest (→ skip these candles)
      · Signals the current phase of the cycle
    """

    name = "volatility_cycle"

    def __init__(self, max_period: int = 30) -> None:
        self.max_period = max_period
        self._dominant_period: int = 0
        self._phase_atr: Dict[int, float] = {}     # phase → normalised ATR
        self._high_vol_phases: List[int] = []
        self._low_vol_phases:  List[int] = []

    def fit(self, df: pd.DataFrame) -> None:
        highs  = df["high"].values.astype(float)
        lows   = df["low"].values.astype(float)
        closes = df["close"].values.astype(float)
        ranges = highs - lows

        # Find dominant volatility period via autocorrelation of squared ranges
        sq_r = ranges ** 2
        acorrs = {}
        for p in range(2, self.max_period + 1):
            if len(sq_r) < p * 3:
                continue
            ac = float(pd.Series(sq_r).autocorr(lag=p))
            if not np.isnan(ac):
                acorrs[p] = ac

        if not acorrs:
            return

        self._dominant_period = max(acorrs, key=lambda k: acorrs[k])
        if acorrs[self._dominant_period] < 0.05:
            return   # no meaningful cycle

        p  = self._dominant_period
        n  = len(ranges)
        phase_ranges: Dict[int, List[float]] = defaultdict(list)
        for i in range(n):
            phase_ranges[i % p].append(ranges[i])

        # Normalise ATR per phase
        all_mean = np.mean(ranges)
        self._phase_atr = {}
        for ph, rl in phase_ranges.items():
            self._phase_atr[ph] = float(np.mean(rl) / (all_mean + 1e-9))

        # High vol phases (>= 1.3× average), low vol phases (<= 0.7×)
        self._high_vol_phases = [ph for ph, v in self._phase_atr.items() if v >= 1.3]
        self._low_vol_phases  = [ph for ph, v in self._phase_atr.items() if v <= 0.7]

        log.debug(
            "VolatilityCycleDetector: period=%d high_vol=%s low_vol=%s",
            p, self._high_vol_phases, self._low_vol_phases,
        )

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if not self._dominant_period or not self._phase_atr:
            return _NEUTRAL

        p            = self._dominant_period
        current_phase = len(df) % p

        atr_ratio = self._phase_atr.get(current_phase, 1.0)

        if current_phase in self._high_vol_phases:
            return AlgoSignal(
                has_pattern=True,
                direction="NEUTRAL",
                confidence=min(0.75, atr_ratio / 2.0),
                detector=self.name,
                description=(
                    f"High-volatility phase (cycle={p}, phase={current_phase}): "
                    f"ATR is {atr_ratio:.1f}× average — larger moves expected"
                ),
                extra={"phase": current_phase, "atr_ratio": atr_ratio,
                       "recommendation": "trade_with_ai"},
            )
        if current_phase in self._low_vol_phases:
            return AlgoSignal(
                has_pattern=True,
                direction="NEUTRAL",
                confidence=0.0,
                detector=self.name,
                description=(
                    f"Low-volatility phase (cycle={p}, phase={current_phase}): "
                    f"ATR is {atr_ratio:.1f}× average — skip this candle"
                ),
                extra={"phase": current_phase, "atr_ratio": atr_ratio,
                       "recommendation": "skip"},
            )
        return _NEUTRAL

    def to_dict(self) -> dict:
        return {
            "period":      self._dominant_period,
            "phase_atr":   {str(k): v for k, v in self._phase_atr.items()},
            "high_vol":    self._high_vol_phases,
            "low_vol":     self._low_vol_phases,
        }

    def from_dict(self, d: dict) -> None:
        self._dominant_period  = d.get("period", 0)
        self._phase_atr        = {int(k): v for k, v in d.get("phase_atr", {}).items()}
        self._high_vol_phases  = d.get("high_vol", [])
        self._low_vol_phases   = d.get("low_vol", [])


# ──────────────────────────────────────────────────────────────────────────────
# 6. Body Ratio Pattern Detector
#    "When the candle body is a specific fraction of the range, what follows?"
# ──────────────────────────────────────────────────────────────────────────────

class BodyRatioPatternDetector:
    """
    OTC algorithms can generate candles with suspiciously uniform body-to-range
    ratios.  If candles with body < 20% range are followed by continuation 80%
    of the time, that's a tradeable pattern.
    """

    name = "body_ratio"

    BUCKETS = [
        (0.00, 0.10, "doji"),
        (0.10, 0.25, "small_body"),
        (0.25, 0.50, "medium_body"),
        (0.50, 0.75, "large_body"),
        (0.75, 1.00, "marubozu"),
    ]

    def __init__(self) -> None:
        self._signals: Dict[str, AlgoSignal] = {}

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        opens  = df["open"].values.astype(float)
        highs  = df["high"].values.astype(float)
        lows   = df["low"].values.astype(float)

        bodies = np.abs(closes - opens)
        ranges = (highs - lows) + 1e-9
        ratios = bodies / ranges
        bull   = (closes >= opens).astype(int)

        self._signals = {}
        # Align to (N-1) so we can always look up bull[i+1]
        ratios_prev = ratios[:-1]
        bull_prev   = bull[:-1]

        for (lo, hi, label) in self.BUCKETS:
            for direction in ("bull", "bear"):
                mask = (ratios_prev >= lo) & (ratios_prev < hi)
                if direction == "bull":
                    mask &= bull_prev.astype(bool)
                else:
                    mask &= (~bull_prev.astype(bool))
                indices = np.where(mask)[0]
                if len(indices) < _MIN_N:
                    continue
                next_bull = bull[indices + 1]
                n         = len(next_bull)
                bc        = int(next_bull.sum())
                br        = bc / n
                res       = scipy_stats.binomtest(bc, n, 0.5)
                p         = float(res.pvalue)
                if p >= _P_CUTOFF or abs(br - 0.5) < 0.08:
                    continue
                next_dir = "CALL" if br > 0.5 else "PUT"
                conf     = _calc_conf(br, p, n)
                key      = f"{direction}_{label}"
                self._signals[key] = AlgoSignal(
                    has_pattern=True, direction=next_dir,
                    confidence=conf, detector=self.name,
                    p_value=p, n_samples=n,
                    description=(
                        f"After {direction} {label} candle "
                        f"(body {lo:.0%}-{hi:.0%} of range): "
                        f"next is {next_dir} {br:.0%} of time"
                    ),
                )
        log.debug("BodyRatioPatternDetector: %d patterns", len(self._signals))

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if not self._signals or len(df) < 2:
            return _NEUTRAL
        c, o = float(df["close"].iloc[-2]), float(df["open"].iloc[-2])
        h, l = float(df["high"].iloc[-2]),  float(df["low"].iloc[-2])
        body  = abs(c - o)
        rng   = (h - l) + 1e-9
        ratio = body / rng
        prev_dir = "bull" if c >= o else "bear"
        for lo, hi, label in self.BUCKETS:
            if lo <= ratio < hi:
                key = f"{prev_dir}_{label}"
                return self._signals.get(key, _NEUTRAL)
        return _NEUTRAL

    def to_dict(self) -> dict:
        return {k: _sig_to_dict(v) for k, v in self._signals.items()}

    def from_dict(self, d: dict) -> None:
        self._signals = {k: _sig_from_dict(v) for k, v in d.items()}


# ──────────────────────────────────────────────────────────────────────────────
# 7. Tick Artifact Detector
#    "Does price jump by an unnaturally fixed pip amount repeatedly?"
# ──────────────────────────────────────────────────────────────────────────────

class TickArtifactDetector:
    """
    Synthetic OTC tick generators sometimes produce price movements that are
    exact multiples of a fixed tick size, at regular intervals.

    If the open-to-close move is exactly 3 pips 40% of the time but the
    distribution says it should be 5%, that's a mechanical pattern.
    """

    name = "tick_artifact"

    def __init__(self, pip_size: float = 0.0001) -> None:
        self.pip_size = pip_size
        self._dominant_move_pips: Optional[float] = None
        self._after_exact_move: Optional[AlgoSignal] = None

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        opens  = df["open"].values.astype(float)
        bull   = (closes >= opens).astype(int)

        moves_pips = np.abs(closes - opens) / self.pip_size
        # Round to nearest 0.5 pip
        rounded = np.round(moves_pips * 2) / 2

        from collections import Counter
        counts = Counter(rounded)
        total  = sum(counts.values())
        if total == 0:
            return

        # Find the most overrepresented move size
        expected = 1.0 / len(counts)
        for move, count in counts.most_common(5):
            observed_rate = count / total
            if observed_rate < expected * 3:
                continue
            if count < _MIN_N:
                continue

            mask      = np.abs(rounded - move) < 0.3
            outcomes  = bull[:-1][mask[:-1] if len(mask) > 1 else mask[:len(bull)-1]]
            # Next candle after an exact-move candle
            next_indices = np.where(mask[:-1])[0] + 1
            if len(next_indices) < _MIN_N:
                continue
            next_bull = bull[next_indices]
            n         = len(next_bull)
            bc        = int(next_bull.sum())
            br        = bc / n
            res       = scipy_stats.binomtest(bc, n, 0.5)
            p         = float(res.pvalue)
            if p >= _P_CUTOFF or abs(br - 0.5) < 0.08:
                continue

            direction = "CALL" if br > 0.5 else "PUT"
            conf      = _calc_conf(br, p, n)
            self._dominant_move_pips  = float(move)
            self._after_exact_move    = AlgoSignal(
                has_pattern=True, direction=direction,
                confidence=conf, detector=self.name,
                p_value=p, n_samples=n,
                description=(
                    f"Exact {move:.1f}-pip move occurred: "
                    f"next candle is {direction} {br:.0%} of time "
                    f"(appears {observed_rate:.0%} vs expected {expected:.0%})"
                ),
            )
            break

        log.debug("TickArtifactDetector: dominant_move=%s", self._dominant_move_pips)

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if self._dominant_move_pips is None or self._after_exact_move is None:
            return _NEUTRAL
        if len(df) < 2:
            return _NEUTRAL
        last_move_pips = (
            abs(float(df["close"].iloc[-2]) - float(df["open"].iloc[-2]))
            / self.pip_size
        )
        if abs(round(last_move_pips * 2) / 2 - self._dominant_move_pips) < 0.4:
            return self._after_exact_move
        return _NEUTRAL

    def to_dict(self) -> dict:
        return {
            "dominant_pips": self._dominant_move_pips,
            "signal":        _sig_to_dict(self._after_exact_move)
                             if self._after_exact_move else None,
        }

    def from_dict(self, d: dict) -> None:
        self._dominant_move_pips = d.get("dominant_pips")
        raw = d.get("signal")
        self._after_exact_move   = _sig_from_dict(raw) if raw else None


# ──────────────────────────────────────────────────────────────────────────────
# 8. Run Length Detector
#    "How many consecutive candles in one direction before a reversal?"
# ──────────────────────────────────────────────────────────────────────────────

class RunLengthDetector:
    """
    If an OTC algorithm limits directional runs (e.g. never more than 4
    consecutive bullish candles without a reversal), that limit is detectable.

    Live use: if current run length is approaching the historical maximum
    → signal a reversal.
    """

    name = "run_length"

    def __init__(self) -> None:
        self._max_bull_run:  int   = 0
        self._max_bear_run:  int   = 0
        self._bull_limit_conf: float = 0.0
        self._bear_limit_conf: float = 0.0

    def fit(self, df: pd.DataFrame) -> None:
        closes = df["close"].values.astype(float)
        opens  = df["open"].values.astype(float)
        bull   = (closes >= opens).astype(int)

        def _run_lengths(direction: int) -> List[int]:
            runs, cur = [], 0
            for b in bull:
                if b == direction:
                    cur += 1
                else:
                    if cur > 0:
                        runs.append(cur)
                    cur = 0
            return runs

        bull_runs = _run_lengths(1)
        bear_runs = _run_lengths(0)

        if not bull_runs or not bear_runs:
            return

        self._max_bull_run = int(np.percentile(bull_runs, 95))
        self._max_bear_run = int(np.percentile(bear_runs, 95))

        # Probability of reversal at exactly max run
        def _reversal_conf(runs: List[int], max_r: int) -> float:
            at_limit  = sum(1 for r in runs if r == max_r)
            above_lim = sum(1 for r in runs if r >  max_r)
            total     = at_limit + above_lim
            if total < 5:
                return 0.0
            reversal_rate = at_limit / total
            return float(min(0.90, reversal_rate))

        self._bull_limit_conf = _reversal_conf(bull_runs, self._max_bull_run)
        self._bear_limit_conf = _reversal_conf(bear_runs, self._max_bear_run)

        log.debug(
            "RunLengthDetector: max_bull_run=%d (conf=%.2f) "
            "max_bear_run=%d (conf=%.2f)",
            self._max_bull_run, self._bull_limit_conf,
            self._max_bear_run, self._bear_limit_conf,
        )

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        if not self._max_bull_run or len(df) < 5:
            return _NEUTRAL

        closes  = df["close"].values.astype(float)
        opens   = df["open"].values.astype(float)
        bull    = (closes >= opens).astype(int)
        current_dir = bull[-2]
        run_len = 1
        for i in range(len(bull) - 3, -1, -1):
            if bull[i] == current_dir:
                run_len += 1
            else:
                break

        if current_dir == 1 and run_len >= self._max_bull_run:
            if self._bull_limit_conf >= _MIN_CONF:
                return AlgoSignal(
                    has_pattern=True, direction="PUT",
                    confidence=self._bull_limit_conf, detector=self.name,
                    description=(
                        f"Bull run={run_len} reached historical max ({self._max_bull_run}): "
                        f"reversal expected ({self._bull_limit_conf:.0%})"
                    ),
                )
        if current_dir == 0 and run_len >= self._max_bear_run:
            if self._bear_limit_conf >= _MIN_CONF:
                return AlgoSignal(
                    has_pattern=True, direction="CALL",
                    confidence=self._bear_limit_conf, detector=self.name,
                    description=(
                        f"Bear run={run_len} reached historical max ({self._max_bear_run}): "
                        f"reversal expected ({self._bear_limit_conf:.0%})"
                    ),
                )
        return _NEUTRAL

    def to_dict(self) -> dict:
        return {
            "max_bull":       self._max_bull_run,
            "max_bear":       self._max_bear_run,
            "bull_conf":      self._bull_limit_conf,
            "bear_conf":      self._bear_limit_conf,
        }

    def from_dict(self, d: dict) -> None:
        self._max_bull_run    = d.get("max_bull",  0)
        self._max_bear_run    = d.get("max_bear",  0)
        self._bull_limit_conf = d.get("bull_conf", 0.0)
        self._bear_limit_conf = d.get("bear_conf", 0.0)


# ──────────────────────────────────────────────────────────────────────────────
# Master Scanner — runs all 8 detectors, returns best signal
# ──────────────────────────────────────────────────────────────────────────────

class AlgoPatternScanner:
    """
    Runs all 8 detectors in one scan and at each live candle
    returns the single highest-confidence signal.

    Integration in advisor.py
    --------------------------
        scanner = AlgoPatternScanner()
        scanner.fit(db.get_candles(asset, 60, limit=5000))
        scanner.save("models/algo_patterns.json")

        # Then in every signal loop:
        algo_sig = scanner.signal(df_recent)
        if algo_sig.has_pattern and algo_sig.confidence > 0.65:
            # Use algo_sig.direction alongside AI signal
    """

    def __init__(self, pip_size: float = 0.0001) -> None:
        self._detectors = [
            SequenceDetector(),
            PriceMagnetDetector(pip_size=pip_size),
            OscillationDetector(),
            MeanReversionTimer(),
            VolatilityCycleDetector(),
            BodyRatioPatternDetector(),
            TickArtifactDetector(pip_size=pip_size),
            RunLengthDetector(),
        ]

    def fit(self, df: pd.DataFrame, verbose: bool = True) -> None:
        """Train all detectors on historical data."""
        log.info("AlgoPatternScanner: fitting on %d candles", len(df))
        for det in self._detectors:
            try:
                det.fit(df)
            except Exception as exc:
                log.warning("%s.fit() failed: %s", det.name, exc)
        if verbose:
            log.info("AlgoPatternScanner: training complete")

    def fit_from_db(
        self,
        db,
        asset:       str = "EURUSD_OTC",
        granularity: int = 60,
        limit:       int = 10_000,
    ) -> None:
        """Convenience: load from Database and fit."""
        df = db.get_candles(asset, granularity, limit=limit)
        if df.empty:
            log.warning("No candles in DB for %s", asset)
            return
        self.fit(df)

    def signal(self, df: pd.DataFrame) -> AlgoSignal:
        """
        Check all detectors against the current candle context.
        Returns the highest-confidence non-neutral signal, or NEUTRAL.
        """
        candidates = []
        for det in self._detectors:
            try:
                sig = det.signal(df)
                if sig.has_pattern and sig.confidence >= _MIN_CONF:
                    candidates.append(sig)
            except Exception as exc:
                log.debug("%s.signal() error: %s", det.name, exc)

        if not candidates:
            return _NEUTRAL

        # Return highest confidence
        best = max(candidates, key=lambda s: s.confidence)
        log.debug("AlgoPatternScanner best: %s", best)
        return best

    def all_signals(self, df: pd.DataFrame) -> List[AlgoSignal]:
        """Return all active signals above _MIN_CONF threshold (sorted by confidence desc)."""
        results = []
        for det in self._detectors:
            try:
                sig = det.signal(df)
                results.append(sig)
            except Exception as exc:
                log.debug("%s error: %s", det.name, exc)
        return sorted(
            [s for s in results if s.has_pattern and s.confidence >= _MIN_CONF],
            key=lambda s: -s.confidence,
        )

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        data = {}
        for det in self._detectors:
            try:
                data[det.name] = det.to_dict()
            except Exception:
                pass
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        log.info("AlgoPatternScanner saved to %s", path)

    def load(self, path: str | Path) -> bool:
        path = Path(path)
        if not path.exists():
            return False
        data = json.loads(path.read_text(encoding="utf-8"))
        for det in self._detectors:
            if det.name in data:
                try:
                    det.from_dict(data[det.name])
                except Exception as exc:
                    log.warning("Could not load %s: %s", det.name, exc)
        log.info("AlgoPatternScanner loaded from %s", path)
        return True

    def report(self, df: pd.DataFrame) -> str:
        """Print-friendly report of all currently active signals."""
        sigs = self.all_signals(df)
        if not sigs:
            return "No algorithmic patterns active for current candle."
        lines = ["=" * 60, "  ACTIVE ALGORITHMIC PATTERNS", "=" * 60]
        for s in sigs:
            mark = "★" if s.confidence > 0.70 else "·"
            lines.append(
                f"  {mark} [{s.detector:<22}]  {s.direction:4}  "
                f"conf={s.confidence:.2f}  | {s.description}"
            )
        lines.append("=" * 60)
        return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def _calc_conf(bias: float, p_value: float, n: int) -> float:
    effect   = abs(bias - 0.5) * 2
    sig      = 1.0 - min(1.0, p_value / _P_CUTOFF)
    sample   = min(1.0, n / (_MIN_N * 5))
    return float(min(0.95, 0.45 * effect + 0.35 * sig + 0.20 * sample))


def _rolling_mean(arr: np.ndarray, w: int) -> np.ndarray:
    out = np.full_like(arr, np.nan)
    for i in range(w - 1, len(arr)):
        out[i] = arr[i - w + 1 : i + 1].mean()
    return out


def _sig_to_dict(s: AlgoSignal) -> dict:
    return {
        "has_pattern": s.has_pattern, "direction": s.direction,
        "confidence":  s.confidence,  "detector":  s.detector,
        "description": s.description, "p_value":   s.p_value,
        "n_samples":   s.n_samples,   "extra":     s.extra,
    }


def _sig_from_dict(d: dict) -> AlgoSignal:
    return AlgoSignal(
        has_pattern=d["has_pattern"], direction=d["direction"],
        confidence=d["confidence"],  detector=d["detector"],
        description=d["description"], p_value=d.get("p_value", 1.0),
        n_samples=d.get("n_samples", 0), extra=d.get("extra", {}),
    )
